### ISSUE TITLE
Layout issue in MS Edge: Profiles stack one upon the other instead of showing as list

### ISSUE THREAD

**Issue by thilo** [cobot/coworkers#17]
see screen shot. Profiles should be displayed one after another but they all stack so only one is visible.
<img width="1673" alt="screen shot 2017-08-25 at 12 51 19" src="https://user-images.githubusercontent.com/8471/29711426-0442be98-8995-11e7-9f4b-bee27c8ae29f.png">

**Comment by Kriesse** [comment]
Still not fixed on production.

The CSS on production is slightly different from what I see in development:

The two support queries for the display property are combined to one:
 `@supports ((display: -ms-grid) or (display: grid))`
They should be separate instead.

My best guess is that this is an autoprefixer issue. 

The issue will go away with Edge 16, which is the next version.
IE is not affected.

**Comment by Kriesse** [comment]
still not fixed :( Investigating.

**Comment by langalex** [comment]
scss service fixed. css in production is now updated. no changes to css needed.

**Comment by Kriesse** [comment]
verified in Edge, issue is fixed.
