### ISSUE TITLE
broken layout

### ISSUE THREAD

**Issue by langalex** [cobot/coworkers#21]
[this commit](https://github.com/cobot/coworkers/commit/f46078a69d8851574cdb7b89abc38e4d29078fdf) removed `.cb-site-main`/`.cb-section`/`.cb-container` around `yield`, which broke the general layout (no left-right margin/padding).

<img width="780" alt="image" src="https://user-images.githubusercontent.com/2173/34827251-d10c5806-f6d9-11e7-950f-121b6e40aedc.png">

re-added them now, but not sure what the intention behind this was, so I created this ticket for you to double-check.

**Comment by Kriesse** [comment]
Closing, as this is fixed now, no need to refactor.
