### ISSUE TITLE
Icon font not working

### ISSUE THREAD

**Issue by thilo** [cobot/coworkers#7]
leading to strange buttons. tested in Firefox and Chrome.
<img width="205" alt="screen shot 2017-04-14 at 17 03 40" src="https://cloud.githubusercontent.com/assets/8471/25057365/aa18ae26-215e-11e7-9852-1bee4bc2a124.png">

**Comment by Kida** [comment]
@thilo I can't start the coworkers app. I have no Idea what to do with this (found in readme): 

> copy the .env.example and fill in the variables

Can you help with it?

**Comment by Kriesse** [comment]
related: https://github.com/upstream/cobot_bots/issues/1

**Comment by Kriesse** [comment]
@langalex @thilo Can't tell from the conversation in https://github.com/upstream/cobot_bots/issues/1 – has this been solved?

**Comment by langalex** [comment]
@Kriesse yes
